"""added duration field to Progression table

Revision ID: 4041b93ac48b
Revises: 743a47be78ff
Create Date: 2020-01-09 09:03:40.386773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4041b93ac48b'
down_revision = '743a47be78ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progression', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progression', 'duration')
    # ### end Alembic commands ###
