"""added is_admin field in User table

Revision ID: 743a47be78ff
Revises: b46c79cbc76d
Create Date: 2020-01-08 14:13:24.447193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743a47be78ff'
down_revision = 'b46c79cbc76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
