"""empty message

Revision ID: 9bc89da271cd
Revises: e6ea4c3bf968
Create Date: 2020-01-12 07:09:57.666575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc89da271cd'
down_revision = 'e6ea4c3bf968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progression', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progression', 'description')
    # ### end Alembic commands ###
